#!/usr/bin/env python3
import socket, sys
url = sys.argv[1] if len(sys.argv) > 1 else sys.stdin.read().strip()
s = socket.socket(socket.AF_UNIX)
s.connect('/tmp/url-open.sock')
s.sendall(url.encode() + b'\n')
s.close() 
