import assert from 'node:assert/strict';
import { readFileSync, statSync } from 'node:fs';
import test from 'node:test';

const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');

test('v2 is an isolated React and Tailwind client using the existing protocol', () => {
  const main = read('web-v2/src/main.jsx');
  const app = read('web-v2/src/App.jsx');
  const api = read('web-v2/src/api.js');
  const constants = read('web-v2/src/constants.js');
  const styles = read('web-v2/src/styles.css');
  const vite = read('vite.config.js');

  assert.match(main, /createRoot/);
  assert.match(main, /<StrictMode>/);
  assert.match(styles, /@import "tailwindcss"/);
  assert.match(styles, /@theme inline/);
  assert.match(styles, /:root\[data-theme="dracula"\]/);
  assert.match(styles, /:root\[data-theme="tailwind-light"\]/);
  assert.match(styles, /:root\[data-theme="tailwind-dark"\]/);
  assert.match(constants, /label: 'Tailwind Light'/);
  assert.match(constants, /label: 'Tailwind Dark'/);
  assert.match(constants, /TERMINAL_MODE_STORAGE_KEY = 'ai-workstream-terminal-mode'/);
  assert.match(constants, /TERMINAL_FONT_STORAGE_KEY = 'ai-workstream-terminal-font'/);
  for (const family of ['Roboto Mono', 'Inconsolata', 'JetBrains Mono', 'Source Code Pro', 'IBM Plex Mono']) {
    assert.match(constants, new RegExp(family));
  }
  for (const asset of [
    'roboto-mono-latin.woff2', 'inconsolata-latin.woff2', 'jetbrains-mono-latin.woff2',
    'source-code-pro-latin.woff2', 'ibm-plex-mono-400-latin.woff2', 'ibm-plex-mono-700-latin.woff2',
  ]) {
    assert.equal(statSync(new URL(`../web-v2/public/fonts/${asset}`, import.meta.url)).size > 10_000, true);
    assert.match(styles, new RegExp(`/v2/fonts/${asset.replaceAll('.', '\\.')}`));
  }
  assert.match(app, /new WebSocket\(`\$\{protocol\}\/\/\$\{location\.host\}\/ws\/events`\)/);
  assert.match(app, /SOCKET_MESSAGE_TYPES\.has\(message\.type\)/);
  assert.match(api, /`\/ws\/all\/\?\$\{query\}`/);
  assert.match(api, /listActivePausedWorkstreams/);
  assert.match(api, /status: 'active_paused'/);
  assert.match(api, /`\/ws\/\$\{encodeURIComponent\(id\)\}\/\?status=all`/);
  assert.match(api, /`\/ws\/\$\{encodeURIComponent\(id\)\}\/\$\{command\}`/);
  assert.match(api, /'\/ws\/scratchpad'/);
  assert.match(vite, /base: '\/v2\/'/);
  assert.match(vite, /outDir: '\.\.\/web\/v2'/);
});

test('v2 sidebar groups active sessions by repository in last-used order', async () => {
  const { groupActiveSessionsByRepo } = await import('../web-v2/src/utils.js');
  const groups = groupActiveSessionsByRepo([
    { id: 1, repo: 'acme/alpha', status: 'active', lastJoined: '2026-08-20T12:00:00Z' },
    { id: 2, repo: 'acme/beta', status: 'paused', lastJoined: '2026-08-26T12:00:00Z' },
    { id: 3, repo: 'acme/alpha', status: 'paused', lastJoined: '2026-08-25T12:00:00Z' },
    { id: 4, repo: 'scratch', type: 'scratchpad', status: 'active', lastJoined: null },
    { id: 5, repo: 'acme/closed', status: 'closed', lastJoined: '2026-08-27T12:00:00Z' },
  ]);
  assert.deepEqual(groups.map((group) => group.label), ['acme/beta', 'acme/alpha', 'Scratchpads']);
  assert.deepEqual(groups[1].items.map((item) => item.id), [3, 1]);
  assert.equal(groups.some((group) => group.label === 'acme/closed'), false);
});

test('v2 retains the session controls and creation widgets as React components', () => {
  const app = read('web-v2/src/App.jsx');
  const activeSidebar = read('web-v2/src/ActiveSessionsSidebar.jsx');
  const bottomTabs = read('web-v2/src/BottomTabs.jsx');
  const detail = read('web-v2/src/SessionDetailModal.jsx');
  const creation = read('web-v2/src/NewSessionModal.jsx');
  const icons = read('web-v2/src/icons.jsx');
  const links = read('web-v2/src/LinkEditor.jsx');
  const localTerminal = read('web-v2/src/LocalTerminal.jsx');
  const sessionWorkspace = read('web-v2/src/SessionWorkspace.jsx');
  const table = read('web-v2/src/SessionTable.jsx');
  const ui = read('web-v2/src/ui.jsx');
  const utils = read('web-v2/src/utils.js');

  assert.doesNotMatch(app, /SessionTable/);
  assert.doesNotMatch(app, /listWorkstreams/);
  assert.doesNotMatch(app, /Items per page/);
  assert.doesNotMatch(app, /Pagination/);
  assert.match(app, /<ActiveSessionsSidebar/);
  assert.match(app, /<SessionWorkspace/);
  assert.doesNotMatch(app, /roles=\{panelsForMode\(panelMode\)\}/);
  assert.doesNotMatch(app, /PANEL_MODE_STORAGE_KEY/);
  assert.doesNotMatch(app, /const \[panelMode, setPanelMode\]/);
  assert.match(app, /\{ \.\.\.body, panels: \[\.\.\.DEFAULT_WORKSPACE_ROLES\] \}/);
  assert.match(app, /workspaceSessions\.map\(\(workspaceSession\) =>/);
  assert.match(app, /key=\{workspaceSession\.id\}/);
  assert.match(app, /visible=\{String\(workspaceSession\.id\) === activeWorkspaceId\}/);
  assert.match(app, /onClose=\{\(\) => closeWorkspace\(workspaceSession\.id\)\}/);
  assert.match(app, /command === 'resume' && result\.workstream/);
  assert.match(app, /command === 'pause' \|\| command === 'close'/);
  assert.match(app, /function created\(item\)/);
  assert.match(app, /activateSession\(item\)/);
  assert.match(app, /bottomTabsRef\.current\?\.hide\(\)/);
  assert.match(app, /focusedPanel\?\.startsWith\('workspace-'\)/);
  assert.match(app, /\[focusedPanel\]/);
  assert.match(app, /listActivePausedWorkstreams/);
  assert.match(app, /const sidebarWidth = sidebarOpen/);
  assert.match(app, /sidebarOpen \? `\$\{sidebarWidthPixels\}px` : '0px'/);
  assert.match(app, /const \[sidebarVisibility, setSidebarVisibility\] = useState\('shown'\)/);
  assert.match(app, /const sidebarOpen = sidebarVisibility === 'shown'/);
  assert.match(app, /const fullscreenSourcesRef = useRef\(new Set\(\)\)/);
  assert.match(app, /function.*reportTerminalFullscreen|const reportTerminalFullscreen/);
  assert.match(app, /current === 'shown' \? 'temporarily-hidden' : current/);
  assert.match(app, /current === 'temporarily-hidden' \? 'shown' : current/);
  assert.match(app, /current === 'shown' \? 'manually-hidden' : 'shown'/);
  assert.doesNotMatch(app, /setSidebarOpen/);
  assert.match(app, /gridTemplateColumns: `\$\{sidebarWidth\}/);
  assert.match(app, /SIDEBAR_WIDTH_STORAGE_KEY/);
  assert.match(app, /localStorage\.setItem\(SIDEBAR_WIDTH_STORAGE_KEY/);
  assert.match(app, /localStorage\.setItem\(TERMINAL_MODE_STORAGE_KEY, terminalMode\)/);
  assert.match(app, /localStorage\.setItem\(TERMINAL_FONT_STORAGE_KEY, terminalFont\)/);
  assert.match(app, /const \[sidebarResizing, setSidebarResizing\]/);
  assert.match(app, /useState\('sidebar-sessions'\)/);
  assert.doesNotMatch(app, /data-panel="main"/);
  assert.doesNotMatch(app, /setFocusedPanel\('main'\)/);
  assert.match(app, /<BottomTabs[\s\S]*leftOffset=\{sidebarWidth\}[\s\S]*layoutResizing=\{sidebarResizing\}/);
  assert.match(app, /ref=\{bottomTabsRef\}/);
  assert.match(app, /REFRESH_DEBOUNCE_MS/);
  assert.doesNotMatch(app, /listRequestRef/);
  assert.match(app, /activeSessionsRequestRef\.current !== requestId/);
  assert.doesNotMatch(app, /controller\.abort\(\)/);
  assert.match(activeSidebar, /groupActiveSessionsByRepo/);
  assert.match(activeSidebar, /aria-expanded=\{!collapsed\}/);
  assert.match(activeSidebar, /Collapse.*sidebar view/);
  assert.match(activeSidebar, /transition-\[grid-template-rows,opacity\]/);
  assert.match(activeSidebar, /name\.replace\(\/\^fritzy\\\//);
  assert.match(activeSidebar, /'…'/);
  assert.match(activeSidebar, /branchState\(item\)/);
  assert.match(activeSidebar, /className=\{`size-3\.5 \$\{state\.color\}`\}/);
  assert.match(activeSidebar, /className=\{`size-2\.5 shrink-0 rounded-full ring-1 \$\{classes\}`\}/);
  assert.match(activeSidebar, /bg-active ring-on-active/);
  assert.match(activeSidebar, /bg-paused ring-on-paused/);
  assert.doesNotMatch(activeSidebar, />\{status\}<\/span>/);
  assert.match(activeSidebar, /active && item\.agentStatus === 'working'/);
  assert.match(activeSidebar, /active && item\.shellStatus === 'working'/);
  assert.match(activeSidebar, /if \(!agentWorking && !shellWorking\) return <SessionStatus status=\{item\.status\} \/>/);
  assert.match(activeSidebar, /inline-flex min-h-5 shrink-0 items-center gap-1 rounded-full px-1\.5 ring-1/);
  assert.match(activeSidebar, /<ProviderIcon provider=\{provider\} className="size-3\.5"/);
  assert.match(activeSidebar, /<ShellIcon className="size-3\.5"/);
  assert.match(activeSidebar, /<Spinner className="size-3" \/>/);
  assert.match(activeSidebar, /role="tablist"[\s\S]*aria-label="Sidebar views"/);
  assert.match(activeSidebar, /function chooseView\(nextView\)/);
  assert.match(activeSidebar, /\['sessions', 'settings'\]\.map/);
  assert.match(activeSidebar, /onClick=\{\(\) => chooseView\(option\)\}/);
  assert.match(activeSidebar, /<AssetIcon name="folder" className="size-5"/);
  assert.match(activeSidebar, /<GearIcon className="size-5"/);
  assert.doesNotMatch(activeSidebar, /writing-mode:vertical-rl/);
  assert.match(activeSidebar, /focusedPanel !== 'sidebar-sessions'/);
  assert.match(activeSidebar, /event\.ctrlKey/);
  assert.match(activeSidebar, /event\.key\.toLowerCase\(\) === 'l'/);
  assert.match(activeSidebar, /onWorkspaceFocus\(\)/);
  assert.match(activeSidebar, /panelRef\.current\?\.focus\(\{ preventScroll: true \}\)/);
  assert.match(activeSidebar, /\['j', 'k', 'h', 'l', 'Enter'\]/);
  assert.match(activeSidebar, /kind: 'group'/);
  assert.match(activeSidebar, /kind: 'session'/);
  assert.match(activeSidebar, /event\.key === 'h'/);
  assert.match(activeSidebar, /setGroupCollapsed\(current\.groupLabel, true\)/);
  assert.match(activeSidebar, /event\.key === 'l'/);
  assert.match(activeSidebar, /setGroupCollapsed\(current\.groupLabel, false\)/);
  assert.match(activeSidebar, /data-sidebar-group=\{group\.label\}/);
  assert.match(activeSidebar, /text-left text-sm font-bold transition-colors/);
  assert.match(activeSidebar, /text-left font-mono text-sm transition-colors/);
  assert.match(activeSidebar, /onClick=\{\(\) => onActivate\(item\)\}/);
  assert.match(activeSidebar, /onDoubleClick=\{\(\) => onOpenDetails\(item\.id\)\}/);
  assert.match(activeSidebar, /min-h-screen/);
  assert.match(activeSidebar, /sticky top-0 grid h-screen/);
  assert.match(activeSidebar, /fixed top-2 z-\[55\] grid w-10/);
  assert.match(activeSidebar, /focusedPanel\?\.startsWith\('sidebar-'\)/);
  assert.match(activeSidebar, /opacity-20 hover:opacity-100 focus-within:opacity-100/);
  assert.match(activeSidebar, /transition-\[left,opacity\]/);
  assert.match(activeSidebar, /style=\{\{ left: sidebarWidth \}\}/);
  assert.match(activeSidebar, /role="separator"/);
  assert.match(activeSidebar, /aria-label="Resize sidebar"/);
  assert.match(activeSidebar, /setPointerCapture/);
  assert.match(activeSidebar, /onResizeEnd\(finalWidth\)/);
  assert.match(activeSidebar, /event\.key !== 'ArrowLeft'/);
  assert.doesNotMatch(activeSidebar, /grid-cols-\[minmax\(0,1fr\)_2\.5rem\]/);
  assert.match(activeSidebar, /data-panel=\{currentPanel\}/);
  assert.match(activeSidebar, /onPointerEnter=\{\(\) => onPanelFocus\(currentPanel\)\}/);
  assert.doesNotMatch(activeSidebar, /grid-cols-2 gap-1 px-1\.5 pt-1/);
  assert.match(activeSidebar, /sidebar-settings-view/);
  assert.doesNotMatch(activeSidebar, /PanelModeToggle/);
  assert.doesNotMatch(activeSidebar, /Panel layout/);
  assert.match(activeSidebar, /id="sidebar-theme"/);
  assert.match(activeSidebar, /id="sidebar-terminal-mode"/);
  assert.match(activeSidebar, /id="sidebar-terminal-font"/);
  assert.match(activeSidebar, /Object\.entries\(TERMINAL_FONTS\)/);
  assert.match(activeSidebar, /<option value="dark">Dark<\/option>/);
  assert.match(activeSidebar, /<option value="light">Light<\/option>/);
  assert.doesNotMatch(app, /<PanelModeToggle/);
  assert.doesNotMatch(app, /aria-label="Theme"/);
  assert.match(app, /fixed right-2 bottom-2 z-\[60\]/);
  assert.doesNotMatch(app, /event\.key === 'j'/);
  assert.doesNotMatch(app, /runTableCommand/);
  assert.match(table, /highlightedId/);
  assert.match(table, /scrollIntoView/);
  assert.match(ui, /event\.key !== 'Escape'/);
  assert.match(utils, /!\/\[gjpqy\]\//);
  assert.match(utils, /pt-\[5px\] pb-\[3px\]/);
  assert.match(app, /<SessionDetailModal/);
  assert.match(app, /<NewSessionModal/);
  assert.match(app, /<BottomTabs/);
  assert.match(bottomTabs, /aria-label="Custom terminals"/);
  assert.match(bottomTabs, /forwardRef\(function BottomTabs/);
  assert.match(bottomTabs, /useImperativeHandle\(ref/);
  assert.match(bottomTabs, /focusLastUsed/);
  assert.match(bottomTabs, /const hideDrawer = useCallback/);
  assert.match(bottomTabs, /const collapseDrawer = useCallback/);
  assert.match(bottomTabs, /if \(!hideDrawer\(\)\) return false/);
  assert.match(bottomTabs, /hide: hideDrawer/);
  assert.match(bottomTabs, /const lastUsedRef = useRef\(null\)/);
  assert.match(bottomTabs, /function navigateTerminal\(id, direction\)/);
  assert.match(bottomTabs, /onPanelNavigate=\{\(direction\) => navigateTerminal\(terminal\.id, direction\)\}/);
  assert.match(bottomTabs, /onNavigateUp=\{onWorkspaceFocus\}/);
  assert.match(bottomTabs, /onToggleSidebar=\{onToggleSidebar\}/);
  assert.match(bottomTabs, /onExit=\{\(\) => closeTerminal\(terminal\.id\)\}/);
  assert.match(bottomTabs, /function AddTerminalButton/);
  assert.match(bottomTabs, /aria-label="New terminal"/);
  assert.match(bottomTabs, /relative z-10 flex h-10[\s\S]*<AddTerminalButton onClick=\{addTerminal\} \/>/);
  assert.match(bottomTabs, /fixed right-0 bottom-0 z-50[\s\S]*<span className="block h-10 min-w-14" aria-hidden="true" \/>/);
  assert.match(bottomTabs, /<ShellIcon className="size-4" \/>/);
  assert.match(bottomTabs, /const \[terminals, setTerminals\] = useState\(\[\]\)/);
  assert.match(bottomTabs, /const nextTerminalNumber = useRef\(1\)/);
  assert.match(bottomTabs, /id: `terminal-\$\{number\}`/);
  assert.match(bottomTabs, /setTerminals\(\(current\) => \[\.\.\.current, terminal\]\)/);
  assert.match(bottomTabs, /chooseTab\(terminal\.id\)/);
  assert.match(bottomTabs, /aria-controls="bottom-terminal-panel"/);
  assert.match(bottomTabs, /fixed right-0 bottom-0 z-50/);
  assert.match(bottomTabs, /focusedPanel\?\.startsWith\('workspace-'\)/);
  assert.match(bottomTabs, /opacity-20 hover:opacity-100 focus-within:opacity-100/);
  assert.match(bottomTabs, /transition-\[left,opacity\]/);
  assert.match(bottomTabs, /fixed top-0 right-0 bottom-0 z-30 cursor-default bg-transparent/);
  assert.match(bottomTabs, /active === terminal\.id/);
  assert.match(bottomTabs, /transition-\[translate,left\]/);
  assert.match(bottomTabs, /queuedTab\.current = id/);
  assert.match(bottomTabs, /reducedMotion \? 0 : TAB_SWITCH_MS/);
  assert.match(bottomTabs, /const pendingRemoval = useRef\(null\)/);
  assert.match(bottomTabs, /withoutTerminal\(current, removed\)/);
  assert.match(bottomTabs, /function closeTerminal\(id\)/);
  assert.match(bottomTabs, /onClose=\{closeTerminal\}/);
  assert.match(bottomTabs, /aria-label=\{`Close \$\{terminal\.label\}`\}/);
  assert.match(bottomTabs, /<XIcon className="size-3\.5" \/>/);
  assert.match(bottomTabs, /current\.filter\(\(terminal\) => terminal\.id !== id\)/);
  assert.doesNotMatch(bottomTabs, /<header/);
  assert.doesNotMatch(bottomTabs, /<h2/);
  assert.doesNotMatch(bottomTabs, /IconButton/);
  assert.match(bottomTabs, /bg-page\/90 shadow-md backdrop-blur-sm/);
  assert.match(bottomTabs, /opacity-20 transition-opacity hover:opacity-100 focus-within:opacity-100/);
  assert.match(bottomTabs, /rounded-t-2xl border-2 bg-page pb-1/);
  assert.doesNotMatch(bottomTabs, /Lorem ipsum/);
  assert.doesNotMatch(bottomTabs, /test 1/);
  assert.match(bottomTabs, /<LocalTerminal/);
  assert.match(bottomTabs, /terminals\.map\(\(terminal\) =>/);
  assert.match(bottomTabs, /visible=\{terminalVisible\}/);
  assert.match(bottomTabs, /focused=\{terminalVisible && focusedPanel === `bottom-\$\{terminal\.id\}`\}/);
  assert.match(bottomTabs, /onPanelFocus\(null\)/);
  assert.match(bottomTabs, /data-panel=\{activePanel \|\| undefined\}/);
  assert.match(bottomTabs, /leftOffset = '0rem'/);
  assert.match(bottomTabs, /transition-\[translate,left\]/);
  assert.match(bottomTabs, /style=\{\{ left: leftOffset \}\}/);
  assert.match(bottomTabs, /onPointerEnter=\{\(\) => \{ if \(activePanel\) onPanelFocus\(activePanel\); \}\}/);
  assert.match(bottomTabs, /fontSize=\{terminal\.fontSize\}/);
  assert.match(bottomTabs, /fullscreen: false/);
  assert.match(bottomTabs, /function toggleFullscreen\(id\)/);
  assert.match(bottomTabs, /fullscreen: !terminal\.fullscreen/);
  assert.match(bottomTabs, /activeFullscreen \? 'h-screen' : 'h-\[calc\(75vh\+2\.5rem\)\]'/);
  assert.match(bottomTabs, /data-terminal-fullscreen=\{activeFullscreen\}/);
  assert.match(bottomTabs, /onToggleFullscreen=\{\(\) => toggleFullscreen\(terminal\.id\)\}/);
  assert.match(bottomTabs, /const fullscreenVisible = drawerOpen && activeFullscreen/);
  assert.match(bottomTabs, /onFullscreenChange\?\.\('bottom-terminals', fullscreenVisible\)/);
  assert.match(bottomTabs, /onFullscreenChange\?\.\('bottom-terminals', false\)/);
  assert.match(bottomTabs, /themeMode=\{terminalMode\}/);
  assert.match(bottomTabs, /fontFamily=\{fontFamily\}/);
  assert.match(bottomTabs, /lazy\(\(\) => import\('\.\/LocalTerminal\.jsx'\)\)/);
  assert.match(localTerminal, /new Terminal/);
  assert.match(localTerminal, /const TERMINAL_THEMES/);
  assert.match(localTerminal, /terminal\.options\.theme = terminalTheme\(themeMode\)/);
  assert.match(localTerminal, /terminal\.options\.fontSize = fontSize/);
  assert.match(localTerminal, /terminal\.options\.fontFamily = fontFamily/);
  assert.match(localTerminal, /document\.fonts\?\.load\(`\$\{fontSize\}px \$\{fontFamily\}`\)/);
  assert.match(localTerminal, /\[fontFamily, fontSize, themeMode\]/);
  assert.doesNotMatch(localTerminal, /MutationObserver/);
  assert.match(localTerminal, /new FitAddon/);
  assert.match(localTerminal, /\/ws\/terminal/);
  assert.match(localTerminal, /terminalQuery\.set\('session', String\(sessionId\)\)/);
  assert.match(localTerminal, /terminalQuery\.set\('role', role\)/);
  assert.match(localTerminal, /type: 'resize'/);
  assert.match(localTerminal, /type: 'input'/);
  assert.match(localTerminal, /terminalRef/);
  assert.match(localTerminal, /focusedRef\.current == null \? autoFocusRef\.current : focusedRef\.current/);
  assert.match(localTerminal, /focused === true \|\| \(focused == null && autoFocus\)/);
  assert.match(localTerminal, /\}, \[visible\]\);/);
  assert.match(localTerminal, /requestAnimationFrame\(\(\) => terminalRef\.current\?\.focus\(\)\)/);
  assert.match(localTerminal, /attachCustomKeyEventHandler/);
  assert.match(localTerminal, /const toggleFullscreenRef = useRef\(onToggleFullscreen\)/);
  assert.match(localTerminal, /const exitRef = useRef\(onExit\)/);
  assert.match(localTerminal, /exitRef\.current\?\.\(message\)/);
  assert.match(localTerminal, /const navigateUpRef = useRef\(onNavigateUp\)/);
  assert.match(localTerminal, /const navigateDownRef = useRef\(onNavigateDown\)/);
  assert.match(localTerminal, /key === 'k' \? navigateUpRef\.current/);
  assert.match(localTerminal, /key === 'j' \? navigateDownRef\.current/);
  assert.match(localTerminal, /controlOnly && \(key === 'j' \|\| key === 'k'\)/);
  assert.match(localTerminal, /if \(direction && controlOnly\)/);
  assert.doesNotMatch(localTerminal, /verticalHandler\(\) !== false/);
  assert.doesNotMatch(localTerminal, /panelNavigateRef\.current\(direction\) === false/);
  assert.match(localTerminal, /key === 'p' && controlOnly/);
  assert.match(localTerminal, /toggleSidebarRef\.current\(\)/);
  assert.match(localTerminal, /key === 'f' && controlOnly/);
  assert.match(localTerminal, /event\.type === 'keydown' && !event\.repeat/);
  assert.match(localTerminal, /toggleFullscreenRef\.current\(\)/);
  assert.match(localTerminal, /event\.preventDefault\(\)/);
  assert.match(localTerminal, /event\.stopPropagation\(\)/);
  assert.match(localTerminal, /panelNavigateRef\.current\(direction\)/);
  assert.match(localTerminal, /return false/);
  assert.match(sessionWorkspace, /roles\.map/);
  assert.match(sessionWorkspace, /const \[panelMode, setPanelMode\] = useState\('two'\)/);
  assert.match(sessionWorkspace, /const roles = useMemo\(\(\) => panelsForMode\(panelMode\), \[panelMode\]\)/);
  assert.match(sessionWorkspace, /<PanelModeToggle value=\{panelMode\} onChange=\{changePanelMode\} \/>/);
  assert.match(sessionWorkspace, /setPanelMode\(nextMode\)/);
  assert.match(sessionWorkspace, /nextMode === 'three' \? 'editor' : 'shell'/);
  assert.match(sessionWorkspace, /const \[fullscreenRole, setFullscreenRole\] = useState\(null\)/);
  assert.match(sessionWorkspace, /\{!fullscreenRole && <header/);
  assert.match(sessionWorkspace, /<\/header>\}/);
  assert.match(sessionWorkspace, /function toggleFullscreen\(role\)/);
  assert.match(sessionWorkspace, /current === role \? null : role/);
  assert.match(sessionWorkspace, /gridTemplateColumns: fullscreenRole \? 'minmax\(0, 1fr\)' : columns/);
  assert.match(sessionWorkspace, /suppressed \? 'hidden' : 'flex'/);
  assert.match(sessionWorkspace, /!fullscreenRole && boundaries\.map/);
  assert.match(sessionWorkspace, /onToggleFullscreen=\{\(\) => toggleFullscreen\(role\)\}/);
  assert.match(sessionWorkspace, /const fullscreenVisible = visible && fullscreenRole !== null/);
  assert.match(sessionWorkspace, /onFullscreenChange\?\.\(fullscreenSource, fullscreenVisible\)/);
  assert.match(sessionWorkspace, /onFullscreenChange\?\.\(fullscreenSource, false\)/);
  assert.match(sessionWorkspace, /role="separator"/);
  assert.match(sessionWorkspace, /setPointerCapture/);
  assert.match(sessionWorkspace, /SPLIT_STORAGE_PREFIX/);
  assert.match(sessionWorkspace, /<LocalTerminal/);
  assert.match(sessionWorkspace, /function TerminalFontControls/);
  assert.match(sessionWorkspace, /Decrease \$\{label\} terminal font size/);
  assert.match(sessionWorkspace, /Increase \$\{label\} terminal font size/);
  assert.match(sessionWorkspace, /fontSize=\{fontSizes\[role\]\}/);
  assert.match(sessionWorkspace, /fontFamily=\{fontFamily\}/);
  assert.match(sessionWorkspace, /themeMode=\{terminalMode\}/);
  assert.match(sessionWorkspace, /FONT_SIZE_STORAGE_PREFIX/);
  assert.match(sessionWorkspace, /session\.issues\?\.length > 0/);
  assert.match(sessionWorkspace, /aria-label="Associated links"/);
  assert.match(sessionWorkspace, /session\.notesPath \|\| session\.issues\?\.length > 0/);
  assert.match(sessionWorkspace, /aria-label="Open session notes directory"/);
  assert.match(sessionWorkspace, /<AssetIcon name="notes" className="size-4" \/>/);
  assert.match(sessionWorkspace, /await onOpenNotes\(session\)/);
  assert.match(sessionWorkspace, /session\.issues\?\.map\(\(issue\) => <LinkPill key=\{issue\.ref\} entry=\{issue\} \/>\)/);
  assert.match(sessionWorkspace, /key=\{role === 'agent' \? `\$\{role\}-\$\{session\.agent\}` : role\}/);
  assert.match(sessionWorkspace, /<AgentToggle/);
  assert.match(sessionWorkspace, /className="ml-auto flex min-w-0 items-center gap-1\.5"/);
  assert.match(sessionWorkspace, /compact/);
  assert.match(sessionWorkspace, /onAgentChange\(session, agent\)/);
  assert.match(app, /onAgentChange=\{changeWorkspaceAgent\}/);
  assert.match(app, /mutate\(item, 'agent-set', \{ agent \}\)/);
  assert.match(sessionWorkspace, /role=\{role\}/);
  assert.match(sessionWorkspace, /visible=\{visible && !suppressed\}/);
  assert.match(sessionWorkspace, /focused=\{visible && !suppressed && focused\}/);
  assert.match(sessionWorkspace, /onPanelNavigate=\{\(direction\) => navigatePanel\(index, direction\)\}/);
  assert.match(sessionWorkspace, /onNavigateDown=\{onBottomTerminalFocus\}/);
  assert.match(sessionWorkspace, /onToggleSidebar=\{onToggleSidebar\}/);
  assert.match(sessionWorkspace, /roles\[index \+ direction\]/);
  assert.match(sessionWorkspace, /index === 0 && direction === -1/);
  assert.match(sessionWorkspace, /onSidebarFocus\(\)/);
  assert.match(app, /onWorkspaceFocus=\{focusActiveWorkspace\}/);
  assert.match(app, /bottomTabsRef\.current\?\.focusLastUsed\(\)/);
  assert.match(app, /onBottomTerminalFocus=\{focusLastBottomTerminal\}/);
  assert.match(app, /onSidebarFocus=\{focusVisibleSidebar\}/);
  assert.match(app, /onToggleSidebar=\{toggleSidebar\}/);
  assert.match(app, /event\.key\.toLowerCase\(\) !== 'p'/);
  assert.match(app, /target\?\.closest\('\.xterm'\)/);
  assert.match(app, /onSidebarFocus=\{focusSessionsSidebar\}/);
  assert.match(app, /onFullscreenChange=\{reportTerminalFullscreen\}/);
  assert.match(app, /onOpenNotes=\{openWorkspaceNotes\}/);
  assert.match(app, /mutate\(item, 'open-notes'\)/);
  assert.match(sessionWorkspace, /visible \? 'flex' : 'hidden'/);
  assert.match(sessionWorkspace, /useLayoutEffect/);
  assert.doesNotMatch(app, /<h1[^>]*>FritzWorks<\/h1>/);
  assert.match(activeSidebar, /<h1[^>]*>FritzWorks<\/h1>/);
  assert.match(activeSidebar, /aria-label="New repository session"/);
  assert.match(activeSidebar, /<AssetIcon name="git-branch"/);
  assert.match(activeSidebar, /aria-label="New scratchpad session"/);
  assert.match(activeSidebar, /<AssetIcon name="folder"/);
  assert.match(detail, /'agent-set'/);
  assert.match(detail, /'panel-toggle'/);
  assert.match(detail, /'issue-add'/);
  assert.match(detail, /'issue-remove'/);
  assert.match(creation, /<RepoCombobox/);
  assert.match(creation, /createRepoSession/);
  assert.match(creation, /createScratchpadSession/);
  assert.match(creation, /panels: \[\.\.\.DEFAULT_WORKSPACE_ROLES\]/);
  assert.doesNotMatch(creation, /PanelToggles/);
  assert.match(creation, /onCreated\(body\.workstream\)/);
  assert.match(links, /provider="linear"/);
  assert.match(links, /provider="github"/);
  assert.match(icons, /return <MaskIcon name=\{name\}/);
  assert.match(icons, /name=\{codex \? 'openai' : 'claude'\}/);
  assert.match(icons, /export function GearIcon/);
  assert.match(table, /focus-\$\{panel\}/);
  assert.match(table, /open-notes/);
});
